### ISSUE TITLE
Missing node(s) option

### ISSUE THREAD

**Issue by brandonros** [vanthome/winston-elasticsearch#102]
Something broke in your latest update

error:

```
/Users/brandonros/foo/node_modules/@elastic/elasticsearch/index.js:52
      throw new ConfigurationError('Missing node(s) option')
      ^

ConfigurationError: Missing node(s) option
    at new Client (/Users/brandonros/foo/node_modules/@elastic/elasticsearch/index.js:52:13)
    at new Elasticsearch (/Users/brandonros/foo/node_modules/winston-elasticsearch/index.js:57:21)
    at Object.<anonymous> (/Users/brandonros/foo/backend/lib/logger.js:16:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/brandonros/foo/backend/lib/db.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

package.json

```
    "winston": "^3.2.1",
    "winston-elasticsearch": "^0.8.2",
```

logger.js

```
const winston = require('winston')
const fs = require('fs')
const Elasticsearch = require('winston-elasticsearch')
const httpContext = require('express-http-context')

const options = {
  level: 'debug',
  format: winston.format.combine(
    winston.format.timestamp(),
    winston.format.json()
  ),
  transports: [
    new winston.transports.Console({
      stderrLevels: ['error']
    }),
    new Elasticsearch({
      level: 'debug',
      clientOpts: {
        host: global.elasticsearch.host,
        httpAuth: global.elasticsearch.httpAuth
      }
    })
  ]
}

var logger = winston.createLogger(options)
```

**Comment by vanthome** [comment]
Well the new ES client has different options, see here the property `node` is probably what you specified as `host`.

```
      "level": "info",
      "clientOpts": {
        "node": "http://elasticsearch:9200"
      }
```

**Comment by brandonros** [comment]
not sure if it makes sense to update the README

**Comment by vanthome** [comment]
Just check our readme, there is no example. The example uses the (unspecified) default host/ node which is localhost.

**Comment by faizan-turing** [comment]
for me it was empty nodeUrl

```
 return new Client({
      node: elasticSearchConfig.endpointUrl, // undefined here
      auth: {
        username: elasticSearchConfig.userName,
        password: elasticSearchConfig.password,
      },
    });
```

**Comment by vanthome** [comment]
So anything missing in the README?

**Comment by ronycohen** [comment]
Hi @vanthome , I really think something is missing in your readme. 
Your example doesn't work at all: 


```
/app/node_modules/@elastic/elasticsearch/index.js:77
      throw new ConfigurationError('Missing node(s) option')
      ^

ConfigurationError: Missing node(s) option
    at new Client (/app/node_modules/@elastic/elasticsearch/index.js:77:13)
    at new ElasticsearchTransport (/app/node_modules/winston-elasticsearch/index.js:71:21)
    at Object.<anonymous> (/app/src/modules/logger.js:20:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/src/index.js:18:16)
```

We don't understand that we have to  declare some E.S Host options.
