### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled error.

### ISSUE THREAD

**Issue by enjoynikon** [vanthome/winston-elasticsearch#124]
When I try to set custom _type by using "messageType" param ,my program throw Unhandled error:
code:
```
let transport;
    if (options.db === LoggerDatabase.ES) {
      transport = new Elasticsearch({
        level: options.level || 'info',
        messageType: options.esType || 'monorepo',
        clientOpts: {
          node: options.esNode || 'http://localhost:9200'
        }
      });
    }

    this.logger = Winston.createLogger({
      transports: [transport]
    });
```

error:
```
(node:78168) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at DerivedLogger.emit (events.js:171:17)
    at DerivedLogger.transportEvent (C:\Users\enjoynikon\projects\monorepo\node_modules\winston\lib\winston\logger.js:625:12)
    at Elasticsearch.emit (events.js:187:15)
    at res.items.forEach (C:\Users\enjoynikon\projects\monorepo\node_modules\winston-elasticsearch\bulk_writer.js:100:26)
    at Array.forEach (<anonymous>)
    at client.bulk.then (C:\Users\enjoynikon\projects\monorepo\node_modules\winston-elasticsearch\bulk_writer.js:98:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:78168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:78168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

subsequently this leads to an error:
```
[winston] Attempt to write logs with no transports {"test":"test","level":"info","message":"test controller"}
```

versions:
 ```
"winston-elasticsearch": "0.8.5",
"winston": "3.2.1",
"winston-transport": "4.3.0",
```

**Comment by vanthome** [comment]
Should be fixed with 0.8.6. If not, please re-open.
