### ISSUE TITLE
ElasticSearch Index Error when using a mapping with constant_keyword

### ISSUE THREAD

**Issue by beanaroo** [vanthome/winston-elasticsearch#147]
An index is created outside of the process using the mapping template:

```json
{
"mappings": {
    "properties": {
      "@timestamp": { "type": "date" },
      "@version": { "type": "keyword" },
      "message": { "type": "text" },
      "severity": { "type": "keyword" },
      "service": { "type": "constant_keyword", "value": "my_service" },
      "fields": {
        "dynamic": true,
        "properties": { }
      }
    }
}
```

With `ensureMappingTemplate: false` the following error is thrown after writing to elasticsearch:
```
Error: ElasticSearch index error
    at /home/mike/Documents/Clubware/src/migration/saasify-importer/node_modules/winston-elasticsearch/bulk_writer.js:134:19
    at Array.forEach (<anonymous>)
    at /home/mike/Documents/Clubware/src/migration/saasify-importer/node_modules/winston-elasticsearch/bulk_writer.js:131:19
    at
```

Removing the mapping for `service` provides no errors.

Using package version `0.9.0` with ElasticSearch `7.7.1`

**Comment by vanthome** [comment]
The problem is probably that your indexed data does not match the mapping. Reopen if you are sure it's an issue in the module.
