### ISSUE TITLE
question: how to debug

### ISSUE THREAD

**Issue by rattkin** [vanthome/winston-elasticsearch#169]
I can send most of the data to apm, but I am often getting errors, that don't come from the APM.

My APM server url is apm.example.com (port implied at 443)

However I'm getting often there errors in my node console:
```
Error caught ConnectionError: connect ETIMEDOUT 172.25.0.4:9200
    at ClientRequest.onError (U:\Users\muj\project-endpoint\node_modules\@elastic\elasticsearch\lib\Connection.js:114:16)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
```
I realize this is not winston problem, but please how can I tell what is Winston trying to do?

I think it comes 30 seconds after sending data (the data gets to APM)

**Comment by vanthome** [comment]
you can set the following environment variable:

`export DEBUG=winston:elasticsearch`

Then you should see debug statements in the console like this:https://github.com/vanthome/winston-elasticsearch/blob/master/bulk_writer.js#L90

This might help to correlate.
