### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ElasticSearch index error.

### ISSUE THREAD

**Issue by frankdavidcorona** [vanthome/winston-elasticsearch#183]
Hi, on high demand writing logs, I'm getting the described error:

```
    (node:494172) UnhandledPromiseRejectionWarning: Error: ElasticSearch index error
    at /home/chaplindev/.../node_modules/winston-elasticsearch/bulk_writer.js:135:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    (node:494172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing 
    inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate 
    the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see 
    https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
    (node:494172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise 
    rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm using it with a custom transport:

```
    const getDefaults = (level = 'info') => ({
      level,
      index: getConfiguration('ELASTICSEARCH_INDEX'),
      clientOpts: {
          node: getConfiguration('ELASTICSEARCH_HOST'),
          auth: {
              username: getConfiguration('ELASTICSEARCH_USERNAME'),
              password: getConfiguration('ELASTICSEARCH_PASSWORD')
          }
      },
      source: getConfiguration('ELASTICSEARCH_SOURCE'),
    });

    const WinstonElasticsearchTransport = {
      /**
       * Create a kibana transport
       * @param {object} options
       * @return {winston.transports.Console}
       */
      create: (_ = {}) => {
          return new ElasticsearchTransport(getDefaults());
      },
  
      /**
       * Add a kibana transport to a winston instance
       * @param {winston.LoggerInstance} instance
       * @param {object} options
       */
      addToInstance(instance) {
          instance.add(ElasticsearchTransport, getDefaults());
      },
  }

  module.exports = WinstonElasticsearchTransport;
```
Sample usage:

```
logger.info({}}
```

Currently running 0.15.3 version.

**Comment by adam-risberg** [comment]
For some reason elastic search is rejecting some of your logs, if this happens winston-elasticsearch will retry sending the problematic logs. Have you noticed any missing logs elastic search?

**Comment by frankdavidcorona** [comment]
> For some reason elastic search is rejecting some of your logs, if this happens winston-elasticsearch will retry sending the problematic logs. Have you noticed any missing logs elastic search?

So far I've not noticed missing logs, but I need to go in deep reading all logs because I'm sending some bulks of logs for some specific actions.

**Comment by Nebojsa92** [comment]
I'm getting same error. It writes one or two documents, but than displays this error. If I change index, it writes 1-2 documents and again throws this error.

**Comment by Nebojsa92** [comment]
> > I'm getting the same error. It writes one or two documents but then displays this error. If I change the index, it writes 1-2 documents and again throws this error.
> > EDIT:
> > The issue for me was disk space for elasticsearch host.
> 
> I keep taking a look, but I do not have any issue with disk space.

Yes. I resolved that problem, but the issue still occurred. I did some further debugging:
 -  I put `console.log(response.body.items[0])` in bulk_writer.js on line 134 where I found more details.
 -  Got following: `{
  index: {
    _index: 'localhost-8080',
    _type: '_doc',
    _id: 'KRLtrHgBYfmpqmHMpjZH',
    status: 400,
    error: {
      type: 'mapper_parsing_exception',
      reason: 'object mapping for [message] tried to parse field [message] as object, but found a concrete value'
    }
  }
}`

Problem for me was: `object mapping for [message] tried to parse field [message] as object, but found a concrete value`
If some log in different format gets to elasticsearch, you get this error. 

It resolved the issue for me.

It might be the same for you, but you might as well get some other message. But this is the way to find the problem.
I hope this helps.

**Comment by vanthome** [comment]
see here: https://vishnuatrai.com/blog/2017/12/20/elasticsearch-mapper-parsing-exception/

Could it be that you log the message somewhere as `logger.info(message)` where the message is an object and in other places it's a string?

**Comment by Nebojsa92** [comment]
> see here: https://vishnuatrai.com/blog/2017/12/20/elasticsearch-mapper-parsing-exception/
> 
> Could it be that you log the message somewhere as `logger.info(message)` where the message is an object and in other places it's a string?

Hello! I managed to resolve that issue by splitting into different indexes. I just wanted to provide a way to @frankdavidcorona to investigate further.
Thanks anyway!

**Comment by adam-risberg** [comment]
I think it would help if the bulk writer logs the errors coming from elastic search. I also had issues with elastic search accepting my logs because some field changed datatype which was difficult to debug.

**Comment by vanthome** [comment]
ok, would it have helped if I output the error on this line:

https://github.com/vanthome/winston-elasticsearch/blob/master/bulk_writer.js#L141

using `console.log()`?

**Comment by vanthome** [comment]
I have done this with version `0.15.4`. Can we close this then?
