### ISSUE TITLE
TypeError: this.client.bulk is not a function

### ISSUE THREAD

**Issue by quantropi-cmckenzie** [vanthome/winston-elasticsearch#184]
Hi all.

Trying to use Winston with Logstash (I guess its how logging to ElasticSearch works these days) and I'm running into a world of issues, but this one is out-of-the-box. With Elasticsearch 0.7.12 (with accompanying Kibana and Logstash) winston-elasticsearch 0.15.4 and winton 3.3.3, when I setup my logger, during runtime when I try to log it gets to the ES transport:

```
const { ElasticsearchTransport } = require('winston-elasticsearch');

...

log_transports.push(new transports.Console({ ... }))
log_transports.push(new transports.File({ ... }))
log_transports.push(new ElasticsearchTransport(
{
                client: {
                    node: 'http://elastic:changeme@127.0.0.1:5005',
                    maxRetries:5,
                    requestTimeout:60000,
                    sniffOnStart: true,
                    log: "info"
                },
                indexPrefix: "logstash",
                level: "info",
                flushInterval: 100
            }
))

const formatRest = (info) => {
    const logString = JSON.stringify(Object.assign({}, info, {
            level: undefined,
            message: undefined,
            timestamp: undefined,
            label: undefined,
            component: undefined
        }))
        // Don't return empty objects
    return logString === '{}' ? '' : logString
}

const logger = createLogger({
    format: format.combine(
        format.label({ label: config.logger.label }),
        format.timestamp(),
        format.printf((info) => {
            const { timestamp, label, level, component } = info
            const componentStr = component ? ` (${component})` : ''
            return `${timestamp} | ${label}${componentStr} | ${level} | ${getRequestId()} | ${info.message} ${formatRest(info)}`
        })
    ),
    level: config.logger.logging.level,
    transports: log_transports
})

...

logger.info(`Server is listening on port ${port}`);
```

Here's the full error:

```
/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston/lib/winston/logger.js:307
      throw ex;
      ^
TypeError: this.client.bulk is not a function
    at BulkWriter.write (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston-elasticsearch/bulk_writer.js:127:6)
    at BulkWriter.flush (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston-elasticsearch/bulk_writer.js:91:15)
    at BulkWriter.tick (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston-elasticsearch/bulk_writer.js:55:8)
    at BulkWriter.append (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston-elasticsearch/bulk_writer.js:112:12)
    at ElasticsearchTransport.log (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston-elasticsearch/index.js:149:21)
    at ElasticsearchTransport._write (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston-transport/index.js:82:19)
    at doWrite (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at ElasticsearchTransport.Writable.write (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/home/test/Development/test_app/build/test_app_admin/backend/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:681:20)
```

Any clues?

I read a single vague SO post about mismatching versions (either ES to Winston, or Winston ro Windows-ES, etc...) so I tried grabbing your 0.7.12 tagged version. Although the included README is pretty much the same as the latest version, `new ElasticsearchTransport()` can't be constructed like in the guidance. I had to `new transports.Elasticsearch()`. No errors, but nothing is logged. I set the `indexPrefix: "logstash"` (which is the default Logstash index) but nothing shows up.

If I try something lame like netcat a json file log, I do get log entries appear in Kibana for the Logstash index:

```
$ nc 127.0.0.1 5000 < test.json

$ cat test.json 
{
       "message" => {
        "someField" => "someValue"
    },
      "@version" => "1",
    "@timestamp" => "2021-04-20T13:31:18.703Z",
          "host" => "0:0:0:0:0:0:0:1",
          "port" => 56812
}
```

I tried commenting out my logger format thinking maybe its my log format, but it doesn't help. 

I also tried watching for packets to port 5000 (Logstash) and 9200 (I started sending logs to ES directly, then switched to Logstash, my mistake) and I don't see anything.

Does Winston-elasticsearch actually log connection or authentication errors? I try putting a non-existant port and IP, and nothing happened. No errors, no logs obviously.

I'm about to drop ElasticSearch and Winston from my project. It feels like there's some unmanaged version/format mismatch going on here that's neither obvious or that people are running into (yet?). Any help would be appreciated. Thank you.

**Comment by quantropi-cmckenzie** [comment]
Debugging it a bit, the bulk_writer.js line 126 calls this.client.bulk() and client doesn't have a bulk function attached. Client is just an object/dict with all my configured client settings. There is a reference to the ES bulk API support: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/bulk_examples.html

The bulk API constructs from an ES module Client object. That object should have the bulk support attached.

```
const { Client } = require('@elastic/elasticsearch')
const client = new Client({
  node: 'http://localhost:9200'
})
```

This is obviously some version/support mismatch. I can't tell what it is though.

**Comment by quantropi-cmckenzie** [comment]
Alright. I'll take the hit and say its user error. I was passing my client options into the ElasticsearchTransport() as `client` not `clientOpts`. Once I did I started getting proper errors, like host unreachable, etc... I'm getting logs proper now. Thanks.
