### ISSUE TITLE
Getting error for node version nvm use v8.9.4 

### ISSUE THREAD

**Issue by vaibhavpatil-symblai** [vanthome/winston-elasticsearch#204]
rror: uncaughtException: Unexpected token *
/Users/vaishnavi/Documents/workspace/prs/conversation-api/node_modules/winston-elasticsearch/node_modules/@elastic/elasticsearch/lib/Helpers.js:75
  async * scrollSearch (params, options = {}) {
        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/vaishnavi/Documents//node_modules/winston-elasticsearch/node_modules/@elastic/elasticsearch/index.js:28:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users//Documents/workspace/prs/-api/node_modules/winston-elasticsearch/index.js:8:20)

**Comment by vaibhavpatil-symblai** [comment]
async * scrollSearch (params, options = {}) {
    if (this[kMetaHeader] !== null) {
      options.headers = options.headers || {}
      options.headers['x-elastic-client-meta'] = this[kMetaHeader] + ',h=s'
    }

**Comment by vanthome** [comment]
Completely unrelated, this error is not even in this module!

**Comment by vaibhavpatil-symblai** [comment]
@vanthome thanks for quick reply  
this error coming out for nvm  v8.9.4, do you require any details from me?

**Comment by vanthome** [comment]
You are abusing this issue tracker, this is not for asking novice questions.
