### ISSUE TITLE
ReferenceError: before is not defined

### ISSUE THREAD

**Issue by 2-amithap** [vanthome/winston-elasticsearch#206]
im getting below error when running the test.js file.

before(() => {
^

ReferenceError: before is not defined
    at Object.<anonymous> (C:\Users\user\Documents\dc-winston-es\test\test.js:53:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by vanthome** [comment]
Probably an issue with your node version.
