### ISSUE TITLE
Problem with Elasticsearch 6.1.4

### ISSUE THREAD

**Issue by JuergenSimon** [vanthome/winston-elasticsearch#63]
Hello,

I am using the following Elasticsearch instance:

```
{
    "name": "DxOVdqU",
    "cluster_name": "docker-cluster",
    "cluster_uuid": "IfOBOgZNQxaAz9U7ZajDEA",
    "version": {
        "number": "6.1.4",
        "build_hash": "d838f2d",
        "build_date": "2018-03-14T08:28:22.470Z",
        "build_snapshot": false,
        "lucene_version": "7.1.0",
        "minimum_wire_compatibility_version": "5.6.0",
        "minimum_index_compatibility_version": "5.0.0"
    },
    "tagline": "You Know, for Search"
}
```

This is running on localhost, port 9200 is mapped, works great via Postman etc. Now when I try to attach winston to this instance and log something, I get no documents in my index and the following error message:

```
Elasticsearch index error { _index: '3jvsbfjd7isxyurccnze',
  _type: '_doc',
  _id: 'ZxBwGmUBCZ46FrMrGSQX',
  status: 400,
  error:
   { type: 'invalid_type_name_exception',
     reason:
      'Document mapping type name can\'t start with \'_\', found: [_doc]' } }
TypeError: callback is not a function
    at bulk.forEach (/Users/simon/Projects/APPICS/src/appics-backend-common/node_modules/winston-elasticsearch/bulk_writer.js:85:36)
    at Array.forEach (<anonymous>)
    at client.bulk.then (/Users/simon/Projects/APPICS/src/appics-backend-common/node_modules/winston-elasticsearch/bulk_writer.js:85:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is currently completely stopping my efforts to use winston for logging from our app. Any idea what I can do to fix this?

**Comment by vanthome** [comment]
Hi Jürgen,

seems like there is already a mapping already in the index named `_doc`?
To make sure you don't, you might want to try with a freshly purged ES instance.

BG, Thomas

**Comment by vanthome** [comment]
Ok, great, can you drop me a private mail to thomas.hoppe@n-fuse.co  maybe?
