### ISSUE TITLE
TypeError: callback is not a function at bulk.forEach (.../node_modules/winston-elasticsearch/bulk_writer.js:85:10)     at process._tickCallback (internal/process/next_tick.js:68:7)

### ISSUE THREAD

**Issue by JuergenSimon** [vanthome/winston-elasticsearch#64]
Hello,

trying to use winston-elasticsearch against elasticsearch instances 6.1.4 or 6.2.4 results in crazy amounts of these error messages:

```
TypeError: callback is not a function
    at bulk.forEach (.../node_modules/winston-elasticsearch/bulk_writer.js:85:36)
    at Array.forEach (<anonymous>)
    at client.bulk.then (.../node_modules/winston-elasticsearch/bulk_writer.js:85:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JuergenSimon** [comment]
This error was due to winston-elasticsearch using winston@3.x while the rest of the project used winston@2.4.1. Updating winston to @3.0.0 everywhere fixed it.
