### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by uptownhr** [vanthome/winston-elasticsearch#67]
I have a basic setup with,

```
new Elasticsearch({
    level: 'debug',
    index: 'api',
    clientOpts: {
      host: '192.168.254.25:9200'
    }
  })
```

logs are coming into ES but i'm seeing an infinite loop of,
```
api_1      | TypeError: callback is not a function
api_1       |     at bulk.forEach (/api/node_modules/winston-elasticsearch/bulk_writer.js:85:36)
api_1       |     at Array.forEach (<anonymous>)
api_1       |     at client.bulk.then (/api/node_modules/winston-elasticsearch/bulk_writer.js:85:10)
api_1       |     at <anonymous>
api_1       |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
api_1       | TypeError: callback is not a function
api_1       |     at bulk.forEach (/api/node_modules/winston-elasticsearch/bulk_writer.js:85:36)
api_1       |     at Array.forEach (<anonymous>)
api_1       |     at client.bulk.then (/api/node_modules/winston-elasticsearch/bulk_writer.js:85:10)
api_1       |     at <anonymous>
api_1       |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Feel like I'm doing a dumb newbie mistake here. Any pointers?

**Comment by vanthome** [comment]
Can you try to run the tests against a local ES instance? Just lunch ES on your machine and do `npm run test`.

**Comment by uptownhr** [comment]
Sorry this was due to a version mismatch of winston.  Losing.
