### ISSUE TITLE
TypeError: callback is not a function

### ISSUE THREAD

**Issue by whoisstan** [vanthome/winston-elasticsearch#69]
I am getting this error when logging a message:

TypeError: callback is not a function

My code:
```js
const winston = require("winston");
const logger = new winston.Logger();
...
if( process.env.ELASTIC_SEARCH_LOGGING_URL ){

  var elasticsearch = require('elasticsearch');
  var client = new elasticsearch.Client({
    host: process.env.ELASTIC_SEARCH_LOGGING_URL,
    log: 'info'
  }); 

  logger.add( 
    require('winston-elasticsearch'),
    {
      client
    }        
  );
}
//this causes the error
logger.info("hi")
```

I am seeing this:

```
clock_1     | TypeError: callback is not a function
clock_1     |     at Elasticsearch.log (/usr/app/node_modules/winston-elasticsearch/index.js:105:5)
clock_1     |     at transportLog (/usr/app/node_modules/winston/lib/winston/logger.js:234:15)
clock_1     |     at /usr/app/node_modules/winston/node_modules/async/lib/async.js:157:13
```

I use node@8.9,winston@2.4.1 and winston-elasticsearch@0.7.0. The ELASTIC_SEARCH_LOGGING_URL env variable is accurate. 

Also posted it here:
https://stackoverflow.com/questions/52823107/winston-elasticsearch-creates-callback-error-when-logging

**Comment by vanthome** [comment]
You have to use Winston 3.x.x with the 0.7.x series of Winston Elasticsearch. Also note that the initialization is different for Winston 3.x.

**Comment by whoisstan** [comment]
That was it! Thank you.
