### ISSUE TITLE
this.client.bulk is not a function getting client issue with 0.7.0 for Elastic 6.3 and Winston 3.1.0

### ISSUE THREAD

**Issue by arindam89** [vanthome/winston-elasticsearch#70]
I am unable to use this transport for the following error stack,

"message":"uncaughtException: this.client.bulk is not a function\nTypeError: this.client.bulk is not a function\n    at BulkWriter.flush (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:67:22)\n

...
Elasticsearch 6.3 (with AWS using aws-elasticsearch-client)
Winston 3.1.0
Winston-elasticsearch 0.7.0

**Comment by arindam89** [comment]
Full stack
```
1|arindam  | {"error":{},"level":"error","message":"uncaughtException: this.client.bulk is not a function\nTypeError: this.client.bulk is not a function\n    at BulkWriter.flush (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:67:22)\n    at BulkWriter.tick (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:46:8)\n    at Timeout.timer.setTimeout [as _onTimeout] (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:38:10)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","stack":"TypeError: this.client.bulk is not a function\n    at BulkWriter.flush (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:67:22)\n    at BulkWriter.tick (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:46:8)\n    at Timeout.timer.setTimeout [as _onTimeout] (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:38:10)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)","exception":true,"date":"Wed Nov 07 2018 22:09:13 GMT+0530 (IST)","process":{"pid":55290,"uid":1147721488,"gid":1896053708,"cwd":"/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp","execPath":"/Users/arpaul/.nvm/versions/node/v8.11.3/bin/node","version":"v8.11.3","argv":["node","/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/server.js","--config=qa2"],"memoryUsage":{"rss":207970304,"heapTotal":172376064,"heapUsed":141817272,"external":26874884}},"os":{"loadavg":[2.31640625,2.38818359375,2.48876953125],"uptime":2183177},"trace":[{"column":22,"file":"/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js","function":"BulkWriter.flush","line":67,"method":"flush","native":false},{"column":8,"file":"/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js","function":"BulkWriter.tick","line":46,"method":"tick","native":false},{"column":10,"file":"/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js","function":"Timeout.timer.setTimeout [as _onTimeout]","line":38,"method":"timer.setTimeout [as _onTimeout]","native":false},{"column":11,"file":"timers.js","function":"ontimeout","line":498,"method":null,"native":false},{"column":5,"file":"timers.js","function":"tryOnTimeout","line":323,"method":null,"native":false},{"column":5,"file":"timers.js","function":"Timer.listOnTimeout","line":290,"method":"listOnTimeout","native":false}]}
1|arindam  | TypeError: this.client.bulk is not a function
1|arindam  |     at BulkWriter.flush (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:67:22)
1|arindam  |     at BulkWriter.tick (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:46:8)
1|arindam  |     at Timeout.timer.setTimeout [as _onTimeout] (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:38:10)
1|arindam  |     at ontimeout (timers.js:498:11)
1|arindam  |     at tryOnTimeout (timers.js:323:5)
1|arindam  |     at Timer.listOnTimeout (timers.js:290:5)
1|arindam  | TypeError: this.client.bulk is not a function
1|arindam  |     at BulkWriter.flush (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:67:22)
1|arindam  |     at BulkWriter.tick (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:46:8)
1|arindam  |     at Timeout.timer.setTimeout [as _onTimeout] (/Users/arpaul/Work/ALLISWELL/VAG/alliswell_nodeapp/node_modules/winston-elasticsearch/bulk_writer.js:38:10)
1|arindam  |     at ontimeout (timers.js:498:11)
1|arindam  |     at tryOnTimeout (timers.js:323:5)
```

**Comment by vanthome** [comment]
well seems like the aws client does nut support the `buld()` method. Can you check that?

**Comment by arindam89** [comment]
As per the code, the module is not trying to do anything special on top of `elasticsearch` client

https://github.com/AntonBazhal/aws-elasticsearch-client/blob/master/index.js#L23

**Comment by vanthome** [comment]
@arindam89 any update on this?

**Comment by vanthome** [comment]
Clsoing due to inactivity.

**Comment by shiva2021** [comment]
Hi.. I am trying to use the below configuration...

`    var esTransportOpts = {
      level: 'info',
      indexPrefix:'testlogs',
      client:{ node: 'http://127.0.0.1:9200' }
    };
    var logger = winston.createLogger({
      transports: [
        new ElasticsearchTransport(esTransportOpts)
      ]
    });

    logger.log({
      level: 'error',
      message: 'Hello distributed log files!',
      "meta": {
        "method": "GET",
        "url": "/work"
      }
    });
`
Am I doing anything wrong? I am getting this error again and again

**Comment by vanthome** [comment]
Which ES client are you using? The AWS client or the standard client?

**Comment by shiva2021** [comment]
Hi @vanthome ,

Actually, I figured out the solution. I was using an incompatible version of winston-elasticsearch. The winston package version that I was using was 3.2.1, but the  winston-elasticsearch version was something other than 0.7.0 which was causing the issue. As soon as I changed the version to 0.7.0, the error went away. Thanks for responding back btw.

Cheers
