### ISSUE TITLE
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `index` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by 1fabiopereira** [vanthome/winston-elasticsearch#89]
I have the following problem:

```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Json.serialize (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/serializers/json.js:26:23)
    at Json.bulkBody (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/serializers/json.js:55:20)
    at Transport.request (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/transport.js:193:24)
    at exec (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/client_action.js:362:20)
    at EsApiClient.action (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/client_action.js:62:16)
    at asPromise (/nodeapps/ms-gateway/node_modules/elasticsearch-client-retry/index.js:35:17)
    at wrapFunction (/nodeapps/ms-gateway/node_modules/elasticsearch-client-retry/index.js:52:14)
    at BulkWriter.write (/nodeapps/ms-gateway/node_modules/winston-elasticsearch/bulk_writer.js:88:22)
    at BulkWriter.flush (/nodeapps/ms-gateway/node_modules/winston-elasticsearch/bulk_writer.js:68:15)
{ Error: [illegal_argument_exception] Malformed action/metadata line [1], expected a simple value for field [_index] but found [START_OBJECT]
    at respond (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/transport.js:315:15)
    at checkRespForFailure (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/transport.js:274:7)
    at HttpConnector.<anonymous> (/nodeapps/ms-gateway/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)
    at IncomingMessage.wrapper (/nodeapps/ms-gateway/node_modules/lodash/lodash.js:4935:19)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 400,
  displayName: 'BadRequest',
  message:
   '[illegal_argument_exception] Malformed action/metadata line [1], expected a simple value for field [_index] but found [START_OBJECT]',
  path: '/_bulk',
  query: { wait_for_active_shards: '1', timeout: '2000ms' },
  body:
   { error:
      { root_cause: [Array],
        type: 'illegal_argument_exception',
        reason:
         'Malformed action/metadata line [1], expected a simple value for field [_index] but found [START_OBJECT]' },
     status: 400 },
  statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Malformed action/metadata line [1], expected a simple value for field [_index] but found [START_OBJECT]"}],"type":"illegal_argument_exception","reason":"Malformed action/metadata line [1], expected a simple value for field [_index] but found [START_OBJECT]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `index` of 'undefined' or 'null'.
    at bulk.forEach (/nodeapps/ms-gateway/node_modules/winston-elasticsearch/bulk_writer.js:64:16)
    at Array.forEach (<anonymous>)
    at BulkWriter.flush (/nodeapps/ms-gateway/node_modules/winston-elasticsearch/bulk_writer.js:64:8)
    at BulkWriter.tick (/nodeapps/ms-gateway/node_modules/winston-elasticsearch/bulk_writer.js:44:8)
    at thiz.client.ping.then (/nodeapps/ms-gateway/node_modules/winston-elasticsearch/bulk_writer.js:145:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

**Comment by vanthome** [comment]
looks like you are trying us a function or object as index. What are you providing as options?

**Comment by 1fabiopereira** [comment]
These are the options I am providing:

```
const customTransport = new ElasticsearchWinston({
  indexPrefix: 'ms-auth',
  indexSuffixPattern: 'YYYY.MM.DD',
  level: 'info',
  client: elasticsearchClient
})

const logger = createLogger({
  level: 'info',
  format: combine(
    timestamp(),
    json()
  ),
  defaultMeta: { service: 'ms-auth' },
  transports: [ customTransport ]
})
```

**Comment by anli-xsigns** [comment]
I have this error too. Often if log is used heavily. I changed

```javascript
bulk.forEach(({ index, type, doc }) => {
  body.push({ index: { _index: index, _type: type, pipeline: this.pipeline } }, doc);
});
debug('bulk writer is going to write', body);
```
to
```javascript
try{
  bulk.forEach(({ index, type, doc }) => {
    body.push({ index: { _index: index, _type: type, pipeline: this.pipeline } }, doc);
  });
  debug('bulk writer is going to write', body);
}
catch (err) {
  console.error('this is bulk');
  console.error(bulk);
  console.error(err.message);
  throw err;
}
```
and watched at the error console. What I see there if the error occurs is that the request entity is either to large (see e. g. https://github.com/elastic/elasticsearch/issues/2902) or the elk server doesn't respond. So it seems that reacting on errors is needed here. But I think the data hasn't been posted so I don't exactely know why this occurs.

**Comment by vanthome** [comment]
@anli-xsigns you are really getting this error: "TypeError: Converting circular structure to JSON"? Can you provide a stack trace?

**Comment by vanthome** [comment]
Any update on this?

**Comment by litti** [comment]
Sorry, have been on holiday and due to changing the log structure the error doesn't occur very often :-) If it occurs the next time I'll provide a stack trace.

**Comment by himanshu-singh1995** [comment]
https://github.com/vanthome/winston-elasticsearch/blob/4a618e5dcfa758c5f2e8baa48a547fe5c2d7a797/bulk_writer.js#L65-L67

Here in the above code, `bulk` is expected to have 3 keys `index`, `type` and `doc` but for each bulk, 2 elements are being added to the `body`

https://github.com/vanthome/winston-elasticsearch/blob/4a618e5dcfa758c5f2e8baa48a547fe5c2d7a797/bulk_writer.js#L105-L111

but here, while rollbacking `this.bulk`, `this.bulk` is being updated to have elements of the `body`. 
I think, here, every 2 elements of the `body` should be merged before adding to the `this.bulk`.

**Comment by zxlin** [comment]
Thanks for the work on this issue everyone. I've been getting this error consistently for the last 3 days. Would this be in a release soon? 

Also what's the best way to handle something like this in the future? Would listening for the `error` event prevent the unhandled promise rejection? and would that be a "safe" thing to do? We had the server crash about 200 times over the last 3 days, while we have HA, it's not ideal to have the server crash that often. Any advice would be helpful, thanks!

**Comment by vanthome** [comment]
The fix for the related issue https://github.com/vanthome/winston-elasticsearch/pull/97 has already been published to NPM. Have you already tried with the latest version?

Your question I cannot answer right now, maybe you let us know?

**Comment by zxlin** [comment]
Wanted to give an update here:

I upgraded to the new @elastic/elasticsearch package and that package does not seem be bubbling up as the error as an unhandled rejection. Will continue to test and will report back.

**Comment by vanthome** [comment]
You are right, I have released it now, pls. check.
